spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/grandbf
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/resources/
  cache:
    jcache:
      config: classpath:ehcache.xml
server:
  port: 8088
#logging:
#  level:
#    logging.level.com.alucardlockon.grandbattlefantasyserver.*: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
    banner: false
swagger:
  version: 1.0
  ui-config:
    show-request-headers: true
    filter: true
    display-request-duration: true
    request-timeout: 5000
  authorization:
    name: Authorization
    key-name: Authorization
  enabled: true
  license: MIT
  description: api文档
  base-package: com.alucardlockon.grandbattlefantasyserver
  termsOfServiceUrl: https://github.com/alucardlockon/grand-battle-fantasy-server

---
# 开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/grandbf
    username: root
    password: 1234

---
# 生产环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/grandbf
    username: root
    password: 1234
swagger:
  enabled: false

---
# 预发布环境
spring:
  profiles: sit
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/grandbf
    username: root
    password: 1234

---
# 测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/grandbf
    username: root
    password: 1234